'use server';

import { revalidatePath } from 'next/cache';
import { createClient } from '@/lib/supabase/server';

/* ── Return types ─────────────────────────────────────────────── */
export type CheckoutResult =
  | { success: true }
  | { error: string };

/* ────────────────────────────────────────────────────────────────
   processCheckout — full transactional cart → purchases flow.

   Schema discovered from profile/page.tsx + actions/transaction.ts:
   • Table: public.purchases
   • Columns per row: { user_id, item_id }
   • `id` and `purchased_at` are auto-generated by Postgres defaults.
   • Price is NOT stored on purchases — it is always read from the
     joined market_items row (consistent with buyGame / ProfilePage).

   Transaction order (fail-safe):
   1. Auth guard (server-verified JWT, never getSession)
   2. Fetch cart_items with item_id — abort if empty
   3. INSERT all rows into public.purchases
      • Skip 23505 (unique) duplicates — user already owns those items.
      • Any other DB error → bail WITHOUT touching the cart.
   4. DELETE cart_items for this user (only after a successful insert)
   5. Revalidate all affected paths
──────────────────────────────────────────────────────────────── */
export async function processCheckout(): Promise<CheckoutResult> {
  const supabase = await createClient();

  /* ── 1. Auth guard ── */
  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) {
    throw new Error('UNAUTHORIZED: Vui lòng đăng nhập để thanh toán.');
  }

  /* ── 2. Fetch cart items ── */
  const { data: cartItems, error: cartError } = await supabase
    .from('cart_items')
    .select('item_id')
    .eq('user_id', user.id);

  if (cartError) {
    console.error('[processCheckout] cart fetch error:', cartError.message);
    return { error: 'Không thể tải giỏ hàng. Vui lòng thử lại.' };
  }

  if (!cartItems || cartItems.length === 0) {
    return { error: 'Giỏ hàng trống' };
  }

  /* ── 3. INSERT into public.purchases (one row per cart item) ──
     We insert all rows in a single batch.
     On 23505 (unique constraint = already owned): skip silently.
     On any other error: bail — do NOT clear the cart. ── */
  const purchasePayload = cartItems.map((ci) => ({
    user_id: user.id,
    item_id: ci.item_id,
  }));

  const { error: insertError } = await supabase
    .from('purchases')
    .insert(purchasePayload);

  if (insertError) {
    // 23505 = unique_violation — user already owns one or more items.
    // This is non-fatal for a batch insert: Postgres will reject the
    // entire batch. Handle by upserting with ignoreDuplicates.
    if (insertError.code === '23505') {
      // Re-attempt with upsert to skip duplicates gracefully.
      const { error: upsertError } = await supabase
        .from('purchases')
        .upsert(purchasePayload, {
          onConflict: 'user_id,item_id',
          ignoreDuplicates: true,
        });

      if (upsertError) {
        console.error('[processCheckout] upsert error:', upsertError.message);
        return { error: 'Lỗi giao dịch. Vui lòng thử lại.' };
      }
    } else {
      // Unknown error — abort the transaction; leave cart intact.
      console.error('[processCheckout] insert error:', insertError.message);
      return { error: 'Lỗi giao dịch. Vui lòng thử lại.' };
    }
  }

  /* ── 4. Clear cart (only reached after a successful insert) ── */
  const { error: deleteError } = await supabase
    .from('cart_items')
    .delete()
    .eq('user_id', user.id);

  if (deleteError) {
    // Purchases are already committed — log but don't surface as error.
    // The user owns the items; the cart will appear stale until they
    // manually remove items, which is a recoverable UX state.
    console.error('[processCheckout] cart clear error:', deleteError.message);
  }

  /* ── 5. Revalidate all affected paths ── */

  // Purge global layout → Navbar cart badge drops to 0.
  revalidatePath('/', 'layout');

  // Sync the profile order history tab.
  revalidatePath('/profile');

  return { success: true };
}
